### ISSUE TITLE
Copyright info doesn't float right on chrome for android

### ISSUE THREAD

**Issue by thirstyice** [Aberhart-school/abe-site#155]
![screenshot_2015-08-29-16-04-43-2](https://cloud.githubusercontent.com/assets/5591891/9564604/ad3ffaba-4e69-11e5-8ccf-580823676416.png)

Doesn't happen on ios, nor on chrome for desktop simulating a Nexus 5
Doesn't happen on current (2015-08-29) github version, only on the version pushed to the main server

**Comment by thirstyice** [comment]
For some reason, only on Android, Google imports scripts into the end of `#footer`.
The result is that the copyright, which is styled as `span:last-child` is no longer the last child.
Switching the class to `span:nth-child(3)` will fix the symptoms, but it would be nice to know why the scripts are there in the first place

**Comment by kid47** [comment]
It's been so long since there was activity...
