### ISSUE TITLE
Website survey?

### ISSUE THREAD

**Issue by thirstyice** [Aberhart-school/abe-site#172]
Is the survey still relevant? I only look at it very rarely, and the answers are pretty predictable, and I don't really think they influence our choices.
Also some of the questions aren't really relevant anymore.

Any comments from @gjwehnes or @kid47?

**Comment by kid47** [comment]
I would say that it is still relevant, but in need of an update. The CBE may be interested in seeing it as well if they're still doing the overhaul of the website

**Comment by thirstyice** [comment]
Is that something you want to do? It is largely your survey.

**Comment by kid47** [comment]
I would be inclined to leave it for whoever needs it, because I don't need it anymore and it wasn't tailored for me anyways. I simply maintained it

**Comment by thirstyice** [comment]
Alright then. @gjwehnes do you have someone who wants to update the survey?

**Comment by thirstyice** [comment]
Until the survey is updated I'm going to remove the link from the website because there's no point in linking to something that's out of date.
